---
title: "hw1_4"
author: "Mahdiazhari Austian & Maximilian Hein"
date: "5/7/2022"
output: html_document
---

```{r}
require(MASS)
require(plyr)
require(reshape2)
require(ggplot2)
set.seed(12345) #set seed for repeatable plots
```


```{r}
# generate covariance matrix for points in `x` using given kernel function


cov_matrix <- function(x, kernel_fn, ...) {
    outer(x, x, function(a, b) kernel_fn(a, b, ...))
}


# given x coordinates, take N draws from kernel function at those points
#for the assignment, we put N=5
draw_samples <- function(x, N, kernel_fn, ...) {
    Y <- matrix(NA, nrow = length(x), ncol = N)
    set.seed(12345)
    for (n in 1:N) {
        K <- cov_matrix(x, kernel_fn, ...)
        Y[, n] <- mvrnorm(1, mu = rep(0, times = length(x)), Sigma = K)
    }
    Y
}
```


```{r}
x <- seq(-5, 5, length.out = 50)  # x-coordinates
N <- 5  # no. of draws
col_list <- c("red", "blue", "black", 'green', 'yellow')  # for line colors
```


```{r}
x
```


```{r}
#Square Exponential Kernel
#sigma is h
#length is lambda
se_kernel <- function(x, y, sigma = 1, length = 1) {
    sigma^2 * exp(- (x - y)^2 / (2 * length^2))
}

```


```{r}
Y <- draw_samples(x, N, kernel_fn = se_kernel, length = 0.1)


plot(range(x), range(Y), xlab = "x", ylab = "y", type = "n",
     main = "SE kernel, lambda = 0.1")
for (n in 1:N) {
    lines(x, Y[, n], col = col_list[n], lwd = 1.5)
}
```

```{r}
Y <- draw_samples(x, N, kernel_fn = se_kernel, length = 1)


plot(range(x), range(Y), xlab = "x", ylab = "y", type = "n",
     main = "SE kernel, lambda = 1")
for (n in 1:N) {
    lines(x, Y[, n], col = col_list[n], lwd = 1.5)
}
```


```{r}
Y <- draw_samples(x, N, kernel_fn = se_kernel, length = 10)


plot(range(x), range(Y), xlab = "x", ylab = "y", type = "n",
     main = "SE kernel, lambda = 10")
for (n in 1:N) {
    lines(x, Y[, n], col = col_list[n], lwd = 1.5)
}
```


```{r}
rq_kernel <- function(x, y, alpha = 1, sigma = 1, length = 1) {
    sigma^2 * (1 + (x - y)^2 / (2 * alpha * length^2))^(-alpha)
}
```


```{r}
par(mfrow = c(1, 3))
for (a in c(0.01, 0.5, 50)) {
    Y <- draw_samples(x, N, kernel_fn = rq_kernel, alpha = a)
    
    plot(range(x), range(Y), xlab = "x", ylab = "y", type = "n",
         main = paste("RQ kernel, alpha =", a))
    for (n in 1:N) {
        lines(x, Y[, n], col = col_list[n], lwd = 1.5)
    }
}
```



```{r}
par(mfrow = c(1, 3))
for (a in c(0.01, 0.5, 1, 10, 20, 50)) {
    Y <- draw_samples(x, N, kernel_fn = rq_kernel, alpha = a, length=1)
    
    plot(range(x), range(Y), xlab = "x", ylab = "y", type = "n",
         main = paste("RQ kernel, alpha =", a))
    for (n in 1:N) {
        lines(x, Y[, n], col = col_list[n], lwd = 1.5)
    }
}
```


With alpha = 50, and length (lambda)=1, it resembles the previous SE kernel:
```{r}

for (a in c(50)) {
    Y <- draw_samples(x, N, kernel_fn = rq_kernel, alpha = a, length=1)
    
    plot(range(x), range(Y), xlab = "x", ylab = "y", type = "n",
         main = paste("RQ kernel, alpha =", a))
    for (n in 1:N) {
        lines(x, Y[, n], col = col_list[n])
    }
}
```

